In [2]:
import pandas as pd
import numpy as np
import re

In [2]:
#JASPAR

In [3]:
tomtom = pd.read_csv("./tomtom_conv1_JASPAR/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom["Query_ID"] = tomtom.index
tomtom

         Target_ID   q-value  Query_ID
Query_ID
Motif_17  MA0620.3  0.067559  Motif_17
Motif_25  MA0136.3  0.039716  Motif_25
Motif_25  MA0518.1  0.039716  Motif_25
Motif_25  MA0761.2  0.039716  Motif_25
Motif_25  MA1955.1  0.058639  Motif_25
...            ...       ...       ...
Motif_85  MA0098.3  0.065355  Motif_85
Motif_85  MA1944.1  0.069696  Motif_85
Motif_85  MA0764.3  0.082421  Motif_85
Motif_85  MA1948.1  0.082421  Motif_85
Motif_85  MA1942.1  0.082421  Motif_85

[99 rows x 3 columns]

In [4]:
tomtom.Query_ID.unique().shape

(7,)

In [5]:
anno = pd.read_table("/media/ggj/Guo-4T-AI/FYT/UU/TFBS/MOTIF_ANNO/JASPAR2022_CORE_vertebrates_motif.anno.tsv", 
                  sep=' ', header=None, index_col=None)
anno

         0         1             2
0    MOTIF  MA0004.1          Arnt
1    MOTIF  MA0006.1     Ahr::Arnt
2    MOTIF  MA0019.1  Ddit3::Cebpa
3    MOTIF  MA0029.1         Mecom
4    MOTIF  MA0030.1         FOXF2
..     ...       ...           ...
836  MOTIF  MA1630.2        ZNF281
837  MOTIF  MA1633.2         BACH1
838  MOTIF  MA1647.2         Prdm4
839  MOTIF  MA0597.2         THAP1
840  MOTIF  MA1540.2         NR5A1

[841 rows x 3 columns]

In [6]:
anno.columns=['Motif','Motif_ID','TF']
anno

     Motif  Motif_ID            TF
0    MOTIF  MA0004.1          Arnt
1    MOTIF  MA0006.1     Ahr::Arnt
2    MOTIF  MA0019.1  Ddit3::Cebpa
3    MOTIF  MA0029.1         Mecom
4    MOTIF  MA0030.1         FOXF2
..     ...       ...           ...
836  MOTIF  MA1630.2        ZNF281
837  MOTIF  MA1633.2         BACH1
838  MOTIF  MA1647.2         Prdm4
839  MOTIF  MA0597.2         THAP1
840  MOTIF  MA1540.2         NR5A1

[841 rows x 3 columns]

In [7]:
tomtom_anno = tomtom.merge(anno, how='inner', left_on="Target_ID", right_on="Motif_ID")
tomtom_anno

   Target_ID   q-value  Query_ID  Motif  Motif_ID           TF
0   MA0620.3  0.067559  Motif_17  MOTIF  MA0620.3         MITF
1   MA0136.3  0.039716  Motif_25  MOTIF  MA0136.3         Elf5
2   MA0518.1  0.039716  Motif_25  MOTIF  MA0518.1        Stat4
3   MA0761.2  0.039716  Motif_25  MOTIF  MA0761.2         ETV1
4   MA1955.1  0.058639  Motif_25  MOTIF  MA1955.1  FOXO1::ELK3
..       ...       ...       ...    ...       ...          ...
94  MA1976.1  0.086824  Motif_79  MOTIF  MA1976.1       ZNF320
95  MA1940.1  0.047320  Motif_85  MOTIF  MA1940.1   ETV2::DRGX
96  MA0625.2  0.047320  Motif_85  MOTIF  MA0625.2       NFATC3
97  MA1944.1  0.069696  Motif_85  MOTIF  MA1944.1   ETV5::DRGX
98  MA1948.1  0.082421  Motif_85  MOTIF  MA1948.1  ETV5::HOXA2

[99 rows x 6 columns]

In [8]:
tomtom_anno.to_csv("./tomtom_conv1_JASPAR/filter_anno.csv")

In [ ]:
#CISBP

In [9]:
tomtom = pd.read_csv("./tomtom_conv1_CISBP/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom["Query_ID"] = tomtom.index
tomtom

             Target_ID   q-value   Query_ID
Query_ID
Motif_4    M00437_2.00  0.049598    Motif_4
Motif_4    M00488_2.00  0.049598    Motif_4
Motif_4    M00468_2.00  0.049598    Motif_4
Motif_4    M00407_2.00  0.057537    Motif_4
Motif_4    M00781_2.00  0.066916    Motif_4
...                ...       ...        ...
Motif_119  M00814_2.00  0.037987  Motif_119
Motif_119  M00810_2.00  0.039053  Motif_119
Motif_119  M00820_2.00  0.039053  Motif_119
Motif_119  M00185_2.00  0.079042  Motif_119
Motif_119  M01297_2.00  0.079042  Motif_119

[259 rows x 3 columns]

In [10]:
tomtom.Query_ID.unique().shape

(12,)

In [11]:
anno = pd.read_csv("/media/ggj/Guo-4T-AI/FYT/UU/TFBS/MOTIF_ANNO/mouse_CISBP_motif_TF_Information.txt", 
                  sep='\t', header=0, index_col=0)

anno = anno[["Motif_ID", "TF_Name", "Family_Name"]]
anno

                 Motif_ID TF_Name Family_Name
TF_ID
T010906_2.00  M00111_2.00  Tfap2a        AP-2
T010906_2.00  M02768_2.00  Tfap2a        AP-2
T010906_2.00  M02769_2.00  Tfap2a        AP-2
T010906_2.00  M02770_2.00  Tfap2a        AP-2
T010906_2.00  M08704_2.00  Tfap2a        AP-2
...                   ...     ...         ...
T350319_2.00  M09448_2.00    Cbfb     Unknown
T350320_2.00  M09449_2.00    Nfyc     Unknown
T350321_2.00  M02722_2.00    Spz1     Unknown
T350322_2.00  M11440_2.00   Fank1     Unknown
T350323_2.00  M09450_2.00    Nrf1     Unknown

[2078 rows x 3 columns]

In [12]:
tomtom_anno = tomtom.merge(anno, how='inner', left_on="Target_ID", right_on="Motif_ID")
tomtom_anno

       Target_ID   q-value   Query_ID     Motif_ID TF_Name       Family_Name
0    M00437_2.00  0.049598    Motif_4  M00437_2.00   Meis2       Homeodomain
1    M00488_2.00  0.049598    Motif_4  M00488_2.00   Meis3       Homeodomain
2    M00468_2.00  0.049598    Motif_4  M00468_2.00  Pknox2       Homeodomain
3    M00407_2.00  0.057537    Motif_4  M00407_2.00   Meis1       Homeodomain
4    M00781_2.00  0.066916    Motif_4  M00781_2.00   Snai1           C2H2 ZF
..           ...       ...        ...          ...     ...               ...
252  M00514_2.00  0.077224   Motif_80  M00514_2.00  Nkx2-4       Homeodomain
253  M00813_2.00  0.037987  Motif_119  M00813_2.00    Esr1  Nuclear receptor
254  M00820_2.00  0.039053  Motif_119  M00820_2.00    Rorb  Nuclear receptor
255  M00185_2.00  0.079042  Motif_119  M00185_2.00    Rara  Nuclear receptor
256  M01297_2.00  0.079042  Motif_119  M01297_2.00    Esr2  Nuclear receptor

[257 rows x 6 columns]

In [13]:
tomtom_anno.to_csv("./tomtom_conv1_CISBP/filter_anno.csv")

In [14]:
#Cistarget

In [2]:
import pandas as pd

In [3]:
tomtom = pd.read_csv("./tomtom_conv1_Cistarget/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
#tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom

,Target_ID,Optimal_offset,p-value,E-value,q-value,Overlap,Query_consensus,Target_consensus,Orientation
Query_ID,,,,,,,,,
Motif_2,taipale_cyt_meth__MTF1_NYTTTGCACACGRYNYN_eDBD_...,6,1.618430e-06,0.015294,0.030387,9,CTCTTCAAA,AGGGCCGTGTGCAAAAG,-
Motif_2,taipale_cyt_meth__MTF1_NYTTTGCACACGRYNYN_eDBD_...,6,3.845720e-06,0.036342,0.036103,9,CTCTTCAAA,AAGGCCGTGTGCAAAAG,-
Motif_3,jaspar__MA0205.2,1,1.533970e-06,0.014496,0.019992,9,AAAGAGGCA,GAAAGAGAGAGA,+
Motif_3,predrem__nrMotif2279,-1,2.126000e-06,0.020091,0.019992,8,AAAGAGGCA,TAGAGACAA,-
Motif_3,predrem__nrMotif565,1,7.702150e-06,0.072785,0.048285,9,AAAGAGGCA,AAAAGAGGCT,-
...,...,...,...,...,...,...,...,...,...
Motif_125,hocomoco__HNF1B_HUMAN.H11MO.1.A,-1,6.780920e-05,0.640797,0.079859,8,TGGTTACTG,AGTTAATGATT,+
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,7.856320e-05,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+
Motif_126,jaspar__MA1365.2,1,2.057160e-06,0.019440,0.038782,9,AGGTACATG,ATGGTAAAAAA,+
Motif_126,predrem__nrMotif2512,0,8.757450e-06,0.082758,0.082549,9,AGGTACATG,TGGTAAATG,+
Motif_127,jaspar__MA1722.1,6,7.012030e-08,0.000663,0.001323,9,CAGCCCTGG,GCATAACTGCCCTGCGTCC,+

In [4]:
import pandas as pd
anno = pd.read_csv("/media/ggj/Guo-4T-AI/Scenicplus_database/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl", 
                  sep='\t', header=0, index_col=0)
anno
anno = anno[["motif_name", "gene_name"]]

/home/ggj/anaconda3/envs/scvi-env/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3508: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [15]:
anno.to_csv('./cistarget_motif_anno.csv')

In [6]:
tomtom_anno = tomtom.merge(anno, how='left', left_on="Target_ID", right_index=True)
tomtom_anno

,Target_ID,Optimal_offset,p-value,E-value,q-value,Overlap,Query_consensus,Target_consensus,Orientation,motif_name,gene_name
Query_ID,,,,,,,,,,,
Motif_2,taipale_cyt_meth__MTF1_NYTTTGCACACGRYNYN_eDBD_...,6,1.618430e-06,0.015294,0.030387,9,CTCTTCAAA,AGGGCCGTGTGCAAAAG,-,NaN,NaN
Motif_2,taipale_cyt_meth__MTF1_NYTTTGCACACGRYNYN_eDBD_...,6,3.845720e-06,0.036342,0.036103,9,CTCTTCAAA,AAGGCCGTGTGCAAAAG,-,NaN,NaN
Motif_3,jaspar__MA0205.2,1,1.533970e-06,0.014496,0.019992,9,AAAGAGGCA,GAAAGAGAGAGA,+,NaN,NaN
Motif_3,predrem__nrMotif2279,-1,2.126000e-06,0.020091,0.019992,8,AAAGAGGCA,TAGAGACAA,-,NaN,NaN
Motif_3,predrem__nrMotif565,1,7.702150e-06,0.072785,0.048285,9,AAAGAGGCA,AAAAGAGGCT,-,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,7.856320e-05,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxa13
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,7.856320e-05,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxb13
Motif_126,jaspar__MA1365.2,1,2.057160e-06,0.019440,0.038782,9,AGGTACATG,ATGGTAAAAAA,+,NaN,NaN
Motif_126,predrem__nrMotif2512,0,8.757450e-06,0.082758,0.082549,9,AGGTACATG,TGGTAAATG,+,NaN,NaN
Motif_127,jaspar__MA1722.1,6,7.012030e-08,0.000663,0.001323,9,CAGCCCTGG,GCATAACTGCCCTGCGTCC,+,NaN,NaN

In [7]:
tomtom_anno[tomtom_anno.motif_name.isna()].Target_ID.unique()
tomtom_anno = tomtom_anno.dropna()

In [8]:
tomtom_anno

,Target_ID,Optimal_offset,p-value,E-value,q-value,Overlap,Query_consensus,Target_consensus,Orientation,motif_name,gene_name
Query_ID,,,,,,,,,,,
Motif_4,swissregulon__hs__SIX4,4,0.000006,0.060370,0.026702,9,TGGTGTCCT,TGATAGGTGTCATTTAT,-,hs__SIX4,Six4
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis1
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis2
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis3
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Pbx1
...,...,...,...,...,...,...,...,...,...,...,...
Motif_125,taipale_tf_pairs__GCM1_HOXB13_RTGCGGGTAATAAAN_CAP,3,0.000050,0.476693,0.073117,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM1_HOXB13_RTGCGGGTAATAAAN_CAP,Hoxb13
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Gcm1
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Gcm2
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxa13
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxb13

In [9]:
tomtom_anno['Query_ID'] = tomtom_anno.index

/tmp/ipykernel_560322/2750350718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomtom_anno['Query_ID'] = tomtom_anno.index

In [10]:
tomtom_anno

,Target_ID,Optimal_offset,p-value,E-value,q-value,Overlap,Query_consensus,Target_consensus,Orientation,motif_name,gene_name,Query_ID
Query_ID,,,,,,,,,,,,
Motif_4,swissregulon__hs__SIX4,4,0.000006,0.060370,0.026702,9,TGGTGTCCT,TGATAGGTGTCATTTAT,-,hs__SIX4,Six4,Motif_4
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis1,Motif_4
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis2,Motif_4
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Meis3,Motif_4
Motif_4,nitta__vis_TGCACC40NAGA_KL_TGACAG_m1_c4,-2,0.000064,0.607548,0.064054,6,TGGTGTCCT,CTGTCA,-,vis_TGCACC40NAGA_KL_TGACAG_m1_c4,Pbx1,Motif_4
...,...,...,...,...,...,...,...,...,...,...,...,...
Motif_125,taipale_tf_pairs__GCM1_HOXB13_RTGCGGGTAATAAAN_CAP,3,0.000050,0.476693,0.073117,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM1_HOXB13_RTGCGGGTAATAAAN_CAP,Hoxb13,Motif_125
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Gcm1,Motif_125
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Gcm2,Motif_125
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxa13,Motif_125
Motif_125,taipale_tf_pairs__GCM2_HOXA13_RTRCGGGTAATAAAN_...,3,0.000079,0.742422,0.087081,9,TGGTTACTG,ATGCGGGTAATAAAA,+,GCM2_HOXA13_RTRCGGGTAATAAAN_CAP_repr,Hoxb13,Motif_125

In [10]:
tomtom_anno.to_csv("./tomtom_conv1_Cistarget/filter_anno.csv")

In [11]:
d = {}
for _, gene in tomtom_anno[["Query_ID", "gene_name"]].iterrows():
    m = gene.Query_ID
    tf = gene.gene_name
    if m not in d.keys():
        d[m] = [tf]
    else:
        tfs = d[m]
        if tf not in tfs:
            d[m].append(tf)

#d["Motif_58"]

In [12]:
for k,v in d.items():
    d[k] = '; '.join(v)

#d["Motif_58"]

In [14]:
filter_tf_anno = pd.DataFrame(d, index=['tfs']).T
filter_tf_anno.to_csv("./tomtom_conv1_Cistarget/filter_tf_anno_1101.csv")
filter_tf_anno

                                                         tfs
Motif_4    Six4; Meis1; Meis2; Meis3; Pbx1; Pbx2; Pbx3; P...
Motif_6                                               Zbtb26
Motif_8    Zfp317; Zbtb12; Etv6; Gatad1; Zbtb25; Elk1; El...
Motif_9    2610021A01Rik; Gm7145; Gm28168; Gm28360; Zfp54...
Motif_12   Crx; Dbp; Hlf; Cebpb; Cebpd; Elk1; Erf; Erg; E...
...                                                      ...
Motif_115                                         Nr4a1; Vdr
Motif_119  Nr4a1; Esrra; Esrrb; Esrrg; Nr5a1; Nr5a2; Creb...
Motif_120   Esrra; Esrrb; Esrrg; Nr5a1; Nr5a2; Zbtb12; Nr4a1
Motif_123                                         Zxdb; Zxdc
Motif_125  Zbtb33; Zfp652; Zbtb12; Gcm1; Gcm2; Hoxa13; Ho...

[64 rows x 1 columns]