In [2]:
import pandas as pd
import numpy as np
import re

In [2]:
#JASPAR

In [3]:
tomtom = pd.read_csv("./tomtom_conv1_JASPAR/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom["Query_ID"] = tomtom.index
tomtom

         Target_ID   q-value  Query_ID
Query_ID
Motif_17  MA0620.3  0.067559  Motif_17
Motif_25  MA0136.3  0.039716  Motif_25
Motif_25  MA0518.1  0.039716  Motif_25
Motif_25  MA0761.2  0.039716  Motif_25
Motif_25  MA1955.1  0.058639  Motif_25
...            ...       ...       ...
Motif_85  MA0098.3  0.065355  Motif_85
Motif_85  MA1944.1  0.069696  Motif_85
Motif_85  MA0764.3  0.082421  Motif_85
Motif_85  MA1948.1  0.082421  Motif_85
Motif_85  MA1942.1  0.082421  Motif_85

[99 rows x 3 columns]

In [4]:
tomtom.Query_ID.unique().shape

(7,)

In [5]:
anno = pd.read_table("/media/ggj/Guo-4T-AI/FYT/UU/TFBS/MOTIF_ANNO/JASPAR2022_CORE_vertebrates_motif.anno.tsv", 
                  sep=' ', header=None, index_col=None)
anno

         0         1             2
0    MOTIF  MA0004.1          Arnt
1    MOTIF  MA0006.1     Ahr::Arnt
2    MOTIF  MA0019.1  Ddit3::Cebpa
3    MOTIF  MA0029.1         Mecom
4    MOTIF  MA0030.1         FOXF2
..     ...       ...           ...
836  MOTIF  MA1630.2        ZNF281
837  MOTIF  MA1633.2         BACH1
838  MOTIF  MA1647.2         Prdm4
839  MOTIF  MA0597.2         THAP1
840  MOTIF  MA1540.2         NR5A1

[841 rows x 3 columns]

In [6]:
anno.columns=['Motif','Motif_ID','TF']
anno

     Motif  Motif_ID            TF
0    MOTIF  MA0004.1          Arnt
1    MOTIF  MA0006.1     Ahr::Arnt
2    MOTIF  MA0019.1  Ddit3::Cebpa
3    MOTIF  MA0029.1         Mecom
4    MOTIF  MA0030.1         FOXF2
..     ...       ...           ...
836  MOTIF  MA1630.2        ZNF281
837  MOTIF  MA1633.2         BACH1
838  MOTIF  MA1647.2         Prdm4
839  MOTIF  MA0597.2         THAP1
840  MOTIF  MA1540.2         NR5A1

[841 rows x 3 columns]

In [7]:
tomtom_anno = tomtom.merge(anno, how='inner', left_on="Target_ID", right_on="Motif_ID")
tomtom_anno

   Target_ID   q-value  Query_ID  Motif  Motif_ID           TF
0   MA0620.3  0.067559  Motif_17  MOTIF  MA0620.3         MITF
1   MA0136.3  0.039716  Motif_25  MOTIF  MA0136.3         Elf5
2   MA0518.1  0.039716  Motif_25  MOTIF  MA0518.1        Stat4
3   MA0761.2  0.039716  Motif_25  MOTIF  MA0761.2         ETV1
4   MA1955.1  0.058639  Motif_25  MOTIF  MA1955.1  FOXO1::ELK3
..       ...       ...       ...    ...       ...          ...
94  MA1976.1  0.086824  Motif_79  MOTIF  MA1976.1       ZNF320
95  MA1940.1  0.047320  Motif_85  MOTIF  MA1940.1   ETV2::DRGX
96  MA0625.2  0.047320  Motif_85  MOTIF  MA0625.2       NFATC3
97  MA1944.1  0.069696  Motif_85  MOTIF  MA1944.1   ETV5::DRGX
98  MA1948.1  0.082421  Motif_85  MOTIF  MA1948.1  ETV5::HOXA2

[99 rows x 6 columns]

In [8]:
tomtom_anno.to_csv("./tomtom_conv1_JASPAR/filter_anno.csv")

In [ ]:
#CISBP

In [9]:
tomtom = pd.read_csv("./tomtom_conv1_CISBP/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom["Query_ID"] = tomtom.index
tomtom

             Target_ID   q-value   Query_ID
Query_ID
Motif_4    M00437_2.00  0.049598    Motif_4
Motif_4    M00488_2.00  0.049598    Motif_4
Motif_4    M00468_2.00  0.049598    Motif_4
Motif_4    M00407_2.00  0.057537    Motif_4
Motif_4    M00781_2.00  0.066916    Motif_4
...                ...       ...        ...
Motif_119  M00814_2.00  0.037987  Motif_119
Motif_119  M00810_2.00  0.039053  Motif_119
Motif_119  M00820_2.00  0.039053  Motif_119
Motif_119  M00185_2.00  0.079042  Motif_119
Motif_119  M01297_2.00  0.079042  Motif_119

[259 rows x 3 columns]

In [10]:
tomtom.Query_ID.unique().shape

(12,)

In [11]:
anno = pd.read_csv("/media/ggj/Guo-4T-AI/FYT/UU/TFBS/MOTIF_ANNO/mouse_CISBP_motif_TF_Information.txt", 
                  sep='\t', header=0, index_col=0)

anno = anno[["Motif_ID", "TF_Name", "Family_Name"]]
anno

                 Motif_ID TF_Name Family_Name
TF_ID
T010906_2.00  M00111_2.00  Tfap2a        AP-2
T010906_2.00  M02768_2.00  Tfap2a        AP-2
T010906_2.00  M02769_2.00  Tfap2a        AP-2
T010906_2.00  M02770_2.00  Tfap2a        AP-2
T010906_2.00  M08704_2.00  Tfap2a        AP-2
...                   ...     ...         ...
T350319_2.00  M09448_2.00    Cbfb     Unknown
T350320_2.00  M09449_2.00    Nfyc     Unknown
T350321_2.00  M02722_2.00    Spz1     Unknown
T350322_2.00  M11440_2.00   Fank1     Unknown
T350323_2.00  M09450_2.00    Nrf1     Unknown

[2078 rows x 3 columns]

In [12]:
tomtom_anno = tomtom.merge(anno, how='inner', left_on="Target_ID", right_on="Motif_ID")
tomtom_anno

       Target_ID   q-value   Query_ID     Motif_ID TF_Name       Family_Name
0    M00437_2.00  0.049598    Motif_4  M00437_2.00   Meis2       Homeodomain
1    M00488_2.00  0.049598    Motif_4  M00488_2.00   Meis3       Homeodomain
2    M00468_2.00  0.049598    Motif_4  M00468_2.00  Pknox2       Homeodomain
3    M00407_2.00  0.057537    Motif_4  M00407_2.00   Meis1       Homeodomain
4    M00781_2.00  0.066916    Motif_4  M00781_2.00   Snai1           C2H2 ZF
..           ...       ...        ...          ...     ...               ...
252  M00514_2.00  0.077224   Motif_80  M00514_2.00  Nkx2-4       Homeodomain
253  M00813_2.00  0.037987  Motif_119  M00813_2.00    Esr1  Nuclear receptor
254  M00820_2.00  0.039053  Motif_119  M00820_2.00    Rorb  Nuclear receptor
255  M00185_2.00  0.079042  Motif_119  M00185_2.00    Rara  Nuclear receptor
256  M01297_2.00  0.079042  Motif_119  M01297_2.00    Esr2  Nuclear receptor

[257 rows x 6 columns]

In [13]:
tomtom_anno.to_csv("./tomtom_conv1_CISBP/filter_anno.csv")

In [14]:
#Cistarget

In [3]:
tomtom = pd.read_csv("./tomtom_conv1_Cistarget/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom

                                                   Target_ID   q-value
Query_ID
Motif_0                                     jaspar__MA1415.1  0.000611
Motif_0    taipale_cyt_meth__ZSCAN16_NANTGTTAACAGAGCCTCN_...  0.000966
Motif_0                      hocomoco__FOXJ3_HUMAN.H11MO.1.B  0.000966
Motif_0                                     jaspar__MA1327.2  0.000996
Motif_0                               swissregulon__mm__Sox5  0.005961
...                                                      ...       ...
Motif_127                                predrem__nrMotif366  0.089759
Motif_127                                   jaspar__MA1967.1  0.089759
Motif_127                               predrem__nrMotif1703  0.089759
Motif_127         dbtfbs__SCRT2_HEK293_ENCSR338DGO_merged_N1  0.089759
Motif_127                                      cisbp__M00608  0.089759

[1935 rows x 2 columns]

In [4]:
import pandas as pd
anno = pd.read_csv("/media/ggj/Guo-4T-AI/Scenicplus_database/motifs-v10nr_clust-nr.chicken-m0.001-o0.0.tbl", 
                  sep='\t', header=0, index_col=0)

anno = anno[["motif_name", "gene_name"]]
anno

/home/ggj/anaconda3/envs/scvi-env/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3508: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

                          motif_name gene_name
#motif_id
metacluster_196.3            EcR_usp     HNF4A
metacluster_196.3            EcR_usp     HNF4G
metacluster_196.3            EcR_usp  HNF4beta
metacluster_196.3            EcR_usp     NR1D1
metacluster_196.3            EcR_usp     NR1D2
...                              ...       ...
metacluster_179.4        YPL089C_419     MEF2A
metacluster_145.8        YPR052C_879     HOXB7
metacluster_145.8        YPR052C_879       TBP
metacluster_145.8        YPR052C_879     TBPL2
yetfasco__YPR086W_1327  YPR086W_1327     GTF2B

[186920 rows x 2 columns]

In [ ]:
#import pandas as pd
#anno = pd.read_csv("/media/ggj/Guo-4T-AI/Scenicplus_database/motifs-v9-nr.mgi-m0.001-o0.0.tbl", 
                  sep='\t', header=0, index_col=0)
#def f(x):
#    x = x.replace('__', '-')
#    x = re.sub(r"swissregulon-.+-", "swissregulon-", x) # swissregulon
#     m = re.match(r"^taipale-(.+?)_(.+?)_(.+?)$")
#    if x.find("taipale") != -1:
#        s = x.split("-")[1].split("_")
#        if len(s) > 3:
#            x = '-'.join(["taipale", s[2], s[0], s[1]])
#    return x
#anno.index = anno.index.map(lambda x: f(x))
#anno = anno[["motif_name", "gene_name"]]
#anno

In [17]:
#anno.to_csv('./cistarget_motif_anno.csv')

In [5]:
tomtom_anno = tomtom.merge(anno, how='left', left_on="Target_ID", right_index=True)
tomtom_anno

,Target_ID,q-value,motif_name,gene_name
Query_ID,,,,
Motif_0,jaspar__MA1415.1,0.000611,NaN,NaN
Motif_0,taipale_cyt_meth__ZSCAN16_NANTGTTAACAGAGCCTCN_...,0.000966,NaN,NaN
Motif_0,hocomoco__FOXJ3_HUMAN.H11MO.1.B,0.000966,NaN,NaN
Motif_0,jaspar__MA1327.2,0.000996,MA1327.2,LHX1
Motif_0,jaspar__MA1327.2,0.000996,MA1327.2,LHX3
...,...,...,...,...
Motif_127,jaspar__MA1967.1,0.089759,MA1967.1,FLI1
Motif_127,jaspar__MA1967.1,0.089759,MA1967.1,TFAP4
Motif_127,predrem__nrMotif1703,0.089759,NaN,NaN
Motif_127,dbtfbs__SCRT2_HEK293_ENCSR338DGO_merged_N1,0.089759,NaN,NaN
Motif_127,cisbp__M00608,0.089759,NaN,NaN

In [6]:
tomtom_anno[tomtom_anno.motif_name.isna()].Target_ID.unique()
tomtom_anno = tomtom_anno.dropna()

In [7]:
tomtom_anno

                        Target_ID   q-value motif_name gene_name
Query_ID
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2      LHX1
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2      LHX3
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2     LMX1A
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2     LMX1B
Motif_0    swissregulon__mm__Sox5  0.005961   mm__Sox5      SOX5
...                           ...       ...        ...       ...
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXI1
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXJ2
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXO1
Motif_127        jaspar__MA1967.1  0.089759   MA1967.1      FLI1
Motif_127        jaspar__MA1967.1  0.089759   MA1967.1     TFAP4

[5648 rows x 4 columns]

In [8]:
tomtom_anno['Query_ID'] = tomtom_anno.index

/tmp/ipykernel_1583878/2750350718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomtom_anno['Query_ID'] = tomtom_anno.index

In [9]:
tomtom_anno

                        Target_ID   q-value motif_name gene_name   Query_ID
Query_ID
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2      LHX1    Motif_0
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2      LHX3    Motif_0
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2     LMX1A    Motif_0
Motif_0          jaspar__MA1327.2  0.000996   MA1327.2     LMX1B    Motif_0
Motif_0    swissregulon__mm__Sox5  0.005961   mm__Sox5      SOX5    Motif_0
...                           ...       ...        ...       ...        ...
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXI1  Motif_127
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXJ2  Motif_127
Motif_127        jaspar__MA1950.1  0.088534   MA1950.1     FOXO1  Motif_127
Motif_127        jaspar__MA1967.1  0.089759   MA1967.1      FLI1  Motif_127
Motif_127        jaspar__MA1967.1  0.089759   MA1967.1     TFAP4  Motif_127

[5648 rows x 5 columns]

In [10]:
tomtom_anno.to_csv("./tomtom_conv1_Cistarget/filter_anno.csv")

In [11]:
d = {}
for _, gene in tomtom_anno[["Query_ID", "gene_name"]].iterrows():
    m = gene.Query_ID
    tf = gene.gene_name
    if m not in d.keys():
        d[m] = [tf]
    else:
        tfs = d[m]
        if tf not in tfs:
            d[m].append(tf)

#d["Motif_58"]

In [12]:
for k,v in d.items():
    d[k] = '; '.join(v)

#d["Motif_58"]

In [13]:
filter_tf_anno = pd.DataFrame(d, index=['tfs']).T
#filter_tf_anno.to_csv("./tomtom_conv1_Cistarget/filter_tf_anno.csv")
filter_tf_anno

                                                         tfs
Motif_0    LHX1; LHX3; LMX1A; LMX1B; SOX5; FOXN3; ALX1; A...
Motif_1    EHF; ELF1; ELF2; ELF5; ELK4; ETV1; ETV4; FEV; ...
Motif_2                                                NFAT5
Motif_3    ERG; ETV1; ETV4; ETV7; FOXI1; FOXJ2; FOXO1; EH...
Motif_9                                            HLF; OTX5
Motif_13   CEBPB; CHURC1; E2F1; E2F6; EBF1; ELF1; ELF2; E...
Motif_15   GFI1; GFI1B; POU6F1; VSX2; MEOX2; GSC; MEOX1; ...
Motif_16   BACH1; BACH2; FOS; FOSB; FOSL2; JUN; JUND; NFE...
Motif_17   ARNT; BHLHE40; MAX; MLX; USF1; NKX2-1; NKX2-2;...
Motif_18   FLI1; TFAP4; ETS1; ETV1; ETV5; GABPA; GABPB1; ...
Motif_19   SCRT1; SCRT2; FLI1; TFAP4; MAX; DLX3; ARNT; BH...
Motif_22   MEIS1; MEIS2; PBX1; PBX3; PBX4; PKNOX1; PKNOX2...
Motif_28   NR1D1; NR1D2; RORA; RORB; RORC; NR2F1; HNF4A; ...
Motif_29                                        SCRT1; SCRT2
Motif_30                          ESRRB; ESRRG; NR5A1; NR5A2
Motif_33                                           NFIA; NF1
Motif_34                                  ELF1; MYBL1; MYBL2
Motif_35   GATA5; GATA6; MEIS1; MEIS2; PBX1; PBX3; PBX4; ...
Motif_39             GLI1; GLI2; GLI3; ZNF410; RREB1; PLAGL1
Motif_40                                         GFI1; GFI1B
Motif_41   ZNF384; CPEB1; ZNF362; ELF1; FLI1; FOXI1; FOXJ...
Motif_42   BCLAF1; ELF1; ELK3; ETV1; ETV4; FLI1; GABPA; H...
Motif_43                               NFYA; NFYB; NFYC; SP2
Motif_47   ETS1; ETV1; ETV5; GABPA; GABPB1; FLI1; TFAP4; ...
Motif_49   ESRRB; ATF1; ATF2; ATF3; ATF4; ATF6; BATF; BAT...
Motif_51   ESRRB; ESRRG; NR5A1; NR5A2; NR4A1; NR2C1; RARB...
Motif_53                                               FOXI1
Motif_54   BCLAF1; EGR1; ELF1; ELF2; ELK3; ELK4; EOMES; E...
Motif_55   BCLAF1; ELK3; ETV1; ETV4; FLI1; HOXB13; HOXD12...
Motif_56                                         FLI1; TFAP4
Motif_58                                        SCRT1; SCRT2
Motif_59                                                NFIA
Motif_60   GATA5; GATA6; CPEB1; ZNF362; IRX3; GATA4; GATA...
Motif_62             HNF1A; LEF1; TCF3; TCF7; TCF7L1; TCF7L2
Motif_64                   GATA4; GATA5; GATA3; NR4A1; GATA6
Motif_65                                                KLF3
Motif_67   NR4A1; ESRRB; ESRRG; NR5A1; NR5A2; MEIS1; MEIS...
Motif_74                                              ZNF692
Motif_78   BCLAF1; ELK3; ETV1; ETV4; FLI1; HOXB13; HOXD12...
Motif_81   LIN28A; LIN28B; YBX1; ESRRB; ESRRG; NR5A1; NR5...
Motif_82                                               ESRRB
Motif_83   NR4A1; ESRRB; ESRRG; NR5A1; NR5A2; NR1D1; NR1D...
Motif_87                                 FOXA1; FOXA2; TBPL2
Motif_88   ZBTB26; STAT1; STAT3; STAT4; ETV7; HSF1; BCLAF...
Motif_90                                   GFI1; GFI1B; IRF6
Motif_92            FOXN3; FOXK1; FOXL2; FOXP1; FOXA1; FOXI1
Motif_93   FOXN3; FOXK1; FOXL2; FOXP1; FOXA1; FOXI1; LHX1...
Motif_98   ATF1; ATF2; ATF3; BATF3; CREB1; CREB3; FOSB; J...
Motif_100  ELK4; DLX2; DLX3; ELK3; ERG; ETS1; ETV5; ETV7;...
Motif_101                                        FLI1; TFAP4
Motif_103         PAX1; PAX5; PAX9; RUNX1; IRF6; ELF1; MYBL1
Motif_109               SCRT1; SCRT2; ID4; TCF3; TCF12; ZEB1
Motif_110                                              GATA5
Motif_117                                   PAX1; PAX5; PAX9
Motif_120  BCLAF1; ELF1; ELK3; ETV1; ETV4; FLI1; GABPA; H...
Motif_122                         GATA5; GATA6; GATA3; GATA4
Motif_123               PBX1; POU2F1; POU2F3; POU3F1; POU3F3
Motif_126  ZBTB26; HSF1; ELF1; ETV7; TEAD4; EHF; ELF2; EL...
Motif_127  SCRT1; SCRT2; PBX1; ERG; ETV1; ETV4; ETV7; FOX...

In [14]:
filter_tf_anno.shape

(59, 1)

In [15]:
filter_tf_anno.to_csv("./tomtom_conv1_Cistarget/filter_tf_anno.csv")